// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWdWfv0RiWFUq7knppfKWISk5I2Ed9iI',
    appId: '1:158167138660:web:2dbd56f9aceaa8f8e0ba71',
    messagingSenderId: '158167138660',
    projectId: 'my-portfolio-ae80b',
    authDomain: 'my-portfolio-ae80b.firebaseapp.com',
    storageBucket: 'my-portfolio-ae80b.firebasestorage.app',
    measurementId: 'G-K4JY0434MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuLPXAXvCnU1mbuf4N_QvhzSJForLmoM',
    appId: '1:158167138660:android:ac6fbd0f20dc7962e0ba71',
    messagingSenderId: '158167138660',
    projectId: 'my-portfolio-ae80b',
    storageBucket: 'my-portfolio-ae80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmD6ADy9Ndh7jXb-bHXsqUx9iguH2Fb3o',
    appId: '1:158167138660:ios:aef702c928267be7e0ba71',
    messagingSenderId: '158167138660',
    projectId: 'my-portfolio-ae80b',
    storageBucket: 'my-portfolio-ae80b.firebasestorage.app',
    iosBundleId: 'com.example.property',
  );
}
